name: bagel_db
description: Dart plugin to retrieve and update data on bageldb. This library allows you to build a backend in a matter of minutes, make REST API requests and manage your content easily
version: 0.1.22
homepage: https://www.bageldb.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  universal_io: ^2.0.4
  localstore: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
