name: Bug report (BagelDB v1)
description: Create a bug report to help us improve
labels: ["kind/bug 🐞", "Qv1"]

# Note: Do NOT use commas(,) in options with 'multiple: true', the issue processing workflow won't be able to label it
body:
  - type: markdown
    attributes:
      value: |
        ### Read Before Proceeding Further

        This form is for submitting a **bug report** for BagelDB Libraries.
        If you are using another version, just seeking help, or you would like to submit a feature request, go back and choose a more suitable option from the list.

        Also, search for your issue in the repo to be sure it doesn't exist already.

        To enter your issue, fill out the form correctly and according to the instructions. Try to be as clear as possible and provide as many details as possible, to help our team better understand the issue and to resolve it faster.
        Issues with an unclear description or lacking information will have a lower priority. They may even get closed without taking action.

        Thanks for your understanding. We truly appreciate your effort to fill out this form!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly and concisely explain the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: repro-url
    attributes:
      label: Reproduction URL
      description: |
        Recreate the issue using one of the following:
        [Codepen](https://codepen.io)
        [jsFiddle](https://jsfiddle.net)
        [Codesandbox](https://codesandbox.io)
        fand hit save then copy-paste the URL here.
        _You can provide a GitHub repo only as a last resort. Keep in mind that it will be prioritized less as it makes the reproduction process slower._
      placeholder: https://codepen.io/bageldb/pen/...
    validations:
      required: true
  - type: textarea
    id: repro-description
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to the provided reproduction link
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: dropdown
    id: flavour
    attributes:
      label: Flavour
      description: Choose the BagelDB library or interface you are using. _The names between parentheses indicate the package names if applicable._
      options:
        - BagelDB Flutter (@bageldb/bageldb-flutter)
        - BagelDB JS (@bageldb/bageldb-js)
        - BagelDB Nuxt (@bageldb/bageldb-nuxt)
        - BagelDB Python (@bageldb/bageldb-python)
        - BagelDB Swift (@bageldb/bageldb-swift)
        - BagelDB Gatsby (@bageldb/gatsbyjs-source-plugin)
        - BagelDB Gridsome Core (@bageldb/gatsbyjs-source-plugin)
        - BagelDB Gridsome Pages (@bageldb/gatsbyjs-pages-plugin)
        - BagelDB Vue Lazy Image (@bageldb/vue-bgl-image)
        - BagelDB Client (https://app.bageldb.com)
        - BagelDB API/DOCS (https://docs.bageldb.com)
    validations:
      required: true
  - type: dropdown
    id: areas
    attributes:
      label: Areas
      description: Mark the areas in which you see the problem on. _The names between parentheses indicate the package names if applicable._
      multiple: true
      options:
        - Components
        - TypeScript Support
        - Content API
        - Content REST-API
        - Meta API
        - Bagel Auth API
        - Bagel Auth REST-API
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Platforms/Browsers
      description: Mark the platforms/browsers in which you see the problem on. _If you select `Other`, please explain it in `Additional context` section._
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Internet Explorer 11
        - iOS
        - Android
        - Electron
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        _This will be automatically formatted into code, so no need for backticks._
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
