name: BagelDB Images Lazy Loader

on:
  push:
    branches:
      - main
    paths:
      - "vue-bgl-image/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - run: |
          cd ./vue-bgl-image
          npm install
      - run: npm publish ./vue-bgl-image --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_KEY}}
