name: Gridsome Pages Plugin

on:
  push:
    branches:
      - master
    paths:
      - "gridsome-pages-bageldb/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/
      - run: |
          cd ./gridsome-pages-bageldb
          npm install
      - run: npm publish ./gridsome-pages-bageldb --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_KEY}}